webapp_user: "springvault"
webapp_group: "springvault"
jdk_version: "1.8.0"
vault_token: ""
vault_secret_path: "secret/my-app/password"
vault_secret_field: "value"
vault_http_addr: ""
vault_role_id: ""
vault_secret_id: ""
